# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
   os: ubuntu-22.04
   apt_packages:
    - clang
   tools:
      python: "3.10"
     # You can also specify other tool versions:
     # nodejs: "16"
     # rust: "1.55"
     # golang: "1.17"

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats: all


sphinx:
  builder: html
  fail_on_warning: false

