site_name: 'Visuelle Programmiersprachen: Low-Code (4)'
site_url: https://docs.ms-muc-docs.de/projects/visual-programming-languages-docs/
repo_url: https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/visual-programming-languages-docs
edit_uri: edit/main/docs/
view_uri: blob/main/docs/
theme:
  name: material
  language: de
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.sections
  - navigation.expand
  - search.suggest
  - search.highlight
  - content.action.edit
  - content.action.view
plugins:
- search

extra_javascript:
- _static/js/expand_tabs.js
- _static/js/nav-toggle.js

markdown_extensions:
- attr_list
- md_in_html
- tables
- fenced_code
- toc:
    permalink: true