flowchart TB
A["Programmiersprachen"] --> B["textuelle Programmiersprachen"]
A--> CL["visuelle Programmiersprachen"]
CL -->E["industrielle v. Programmiersprachen"]
E --> H["LabVIEW"]
E --> F["IEC 61131-3"]
E --> G["IEC 61499"]
F --> IL
F --> LD
F --> FBD
F --> SFC
F --> ST
G --> FB
G --> EEC
