flowchart TB
A["Programmiersprachen"] --> B["textuelle Programmiersprachen"]
B --> Python
B --> Java
B --> C++
B --> C
B --> C#
A--> CL["visuelle Programmiersprachen"]
CL -->D["erziehungsorientierte v. Programmiersprachen"]
D --> Scratch
D --> Blockly
CL -->E["industrielle v. Programmiersprachen"]
CL -->Informatik
Informatik --> UML

